import { NextResponse } from 'next/server'
import { getActiveScenario, appendAuditLog } from '@/lib/serverTelemetry'

export async function POST() {
  const scenario = getActiveScenario()

  let briefing = ''
  if (scenario === 'spe') {
    briefing =
      '### 🚨 CRITICAL FLIGHT SURGEON BRIEFING: SOLAR PARTICLE EVENT ACTIVE\n\n' +
      '**Mission Elapsed Time:** Day 142 | Deep Space Transit (Artemis Mars)\n' +
      '**Operational Authority:** Edge Autonomous Medical Command (Ground Comms Latency: 20m 00s)\n\n' +
      '**1. Immediate Clinical Summary:**\n' +
      '- **ASTRO-02 (Mark Jensen, Lead EVA):** Critical radiation spike to **87.4 mGy/day** (SPE EMERGENCY). Autonomic distress observed (HR 102 bpm, HRV RMSSD 18.5 ms). Immediate storm shelter ingress ordered.\n' +
      '- **Fleet Dosimetry:** ASTRO-01 (22.1 mGy), ASTRO-03 (18.7 mGy), ASTRO-04 (15.3 mGy) showing elevated particle flux confirming Coronal Mass Ejection impact.\n\n' +
      '**2. Mandatory Autonomous Countermeasures:**\n' +
      '- **PROT-RAD-SPE-03:** All EVA operations terminated immediately. Crew in water-wall storm shelter within 15 minutes.\n' +
      '- Prescribe antioxidant radioprotective regimen to ASTRO-02.\n\n' +
      '**3. Earth Ground Status:**\n' +
      'Ground telemetry in transit (22m delay). AI decision executed autonomously without ground dependency.'
  } else if (scenario === 'co2_spike') {
    briefing =
      '### ⚠️ SYSTEMS CRITICAL BRIEFING: ECLSS CO₂ SCRUBBER DEGRADATION\n\n' +
      '**Mission Elapsed Time:** Day 142 | Deep Space Transit\n' +
      '**Environmental Warning:** Cabin CO₂ at **5,120 ppm** (Threshold: 4,500 ppm).\n\n' +
      '**1. Cross-Crew Physiological Impact:**\n' +
      '- Fleet-wide morning cognitive fog and PVT reaction time degradation (ASTRO-02: 358 ms, ASTRO-03: 372 ms).\n' +
      '- Mild respiratory acidosis risk. SpO₂ lowered across all 4 crew members (94.2% - 95.8%).\n\n' +
      '**2. Prescribed Countermeasures:**\n' +
      '- **PROT-CO2-HYPERCAPNIA-02:** Auxiliary Amine Swing Bed override initiated. Air exchange increased to 120%.\n' +
      '- All vigorous exercise protocols suspended until ambient CO₂ < 2,800 ppm.'
  } else if (scenario === 'parmitano_eva') {
    briefing =
      '### 🏛️ HISTORICAL BENCHMARK: PARMITANO EVA-23 WATER INTRUSION\n\n' +
      '**Incident Replay:** July 16, 2013 | NASA EVA-23 Investigation Alignment\n' +
      '**Detection Latency:** AegisCrew AI detected anomaly at **T+90s** (vs. NASA actual T+8min).\n\n' +
      '**1. Diagnostic Telemetry:**\n' +
      '- **ASTRO-02 (Parmitano):** SpO₂ collapsed to **93.1%**, heart rate spiked to **118 bpm**, HRV collapsed to **9.2 ms** (severe autonomic panic response).\n' +
      '- Physical cause: Liquid cooling garment water intrusion into helmet occluding breathing passages.\n\n' +
      '**2. Countermeasure Execution:**\n' +
      '- **PROT-EVA-ABORT-23:** Immediate EVA termination and emergency airlock ingress.'
  } else {
    briefing =
      '### 🟢 CHIEF MEDICAL OFFICER DAILY EXECUTIVE BRIEFING\n\n' +
      '**Mission Status:** Nominal Cruise | Artemis Mars Transit (Deep Space Habitat)\n' +
      '**Fleet Readiness:** 94.5% [GREEN] — All 4 crew digital twins in stable equilibrium.\n\n' +
      '**1. Crew Biometric Surveillance:**\n' +
      '- **ASTRO-01 (Commander Vance):** Resting HR 58 bpm, HRV 62 ms, PVT 215 ms. Nominal.\n' +
      '- **ASTRO-02 (Jensen):** Baseline vitals stable. Radiation dosimetry nominal (0.18 mGy/day).\n' +
      '- **ASTRO-03 (Thorne) & ASTRO-04 (Lin):** Circadian rhythms aligned. No acute clinical anomalies.\n\n' +
      '**2. Proactive Recommendations:**\n' +
      '- Maintain standard 8.0h sleep schedule and 2.5h daily countermeasure exercise.'
  }

  appendAuditLog('FLEET', 'BRIEFING_GENERATED', 'Daily Executive Briefing Generated by IBM Granite 4 Medical AI', { scenario })

  return NextResponse.json({
    briefing,
    generated_at: new Date().toISOString(),
    model_used: 'ibm/granite-4-h-small (Deep Space Edge Autonomy)',
    mock_mode: true,
  })
}
